:source-highlighter: highlightjs
:highlightjs-languages: javascript, xml, css, bash, typescript
:icons: font

# ICELL-DATA-TABLE

image:https://img.shields.io/github/license/i-Cell-Mobilsoft-Open-Source/icell-data-table[link="https://github.com/i-Cell-Mobilsoft-Open-Source/icell-data-table/blob/main/LICENSE", License] image:https://img.shields.io/npm/v/@i-cell/data-table[link="https://www.npmjs.com/package/@i-cell/data-table", npm] image:https://img.shields.io/npm/dt/@i-cell/data-table[npm] image:https://github.com/i-Cell-Mobilsoft-Open-Source/icell-data-table/workflows/CI/badge.svg[Build]

## Installation

[source, bash, subs="verbatim,quotes"]
----
npm i _@i-cell/data-table_
----

== Usage

=== Configuration

IMPORTANT: The table uses `materialdesignicons` svg icon, you will need to download the latest `mdi.svg` from https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B[here]. Place the downloaded svg inside the `assets/` folder of your application.

NOTE: If you structure your `assets/` folder in a specific way, you have the option to set the path of the svg, while you import the module.

[source, typescript, subs="verbatim,quotes"]
----
import { DataTableModule } from '@icell/widget-data-table';
import { MatTableModule } from '@angular/material/table';
import { TranslateModule } from '@ngx-translate/core';
import { NgxWebstorageModule } from 'ngx-webstorage';
...

const pathToSvg: string = 'assets/path-to-svg/mdi.svg';

@NgModule({
  ...
  imports: [
    ...
    *DataTableModule.forRoot(pathToSvg),*
    MatTableModule,
    TranslateModule.forRoot(),
    NgxWebstorageModule.forRoot(),
    ...
  ],
  ...
})
export class Module {
  ...
}
----

=== General

==== Column settings

|===
| Property | Type | Optional | Default | Description

| field | `string` | &#10004;&#65039; |  | Path to field that should be rendered.
| orderName | `string` | &#10004;&#65039; |  | Custom ordering parameter.
| valueFormatter | `function` | &#10004;&#65039; |  | Callback to transform the cell's data.
| valueGetter | `function` | &#10004;&#65039; |  | Callback to transform the row model to a displayable value.
| label | `string` | &#10060; |  | Column label; can be a localization key.
| hideable | `boolean` | &#10060; |  | Defines if the column dis hideable.
| visible | `boolean` | &#10060; |  | Defines if the column is visible. If used with hideable, the column will be in the column menu unchecked.
| sortable | `boolean` | &#10004;&#65039; |  | Defines if the column should be sortable.
| sticky | `boolean` | &#10004;&#65039; |  | Defines if the column should be sticky at the begining of the table.
| stickyEnd | `boolean` | &#10004;&#65039; |  | Defines if the column should be sticky at the end of the table.
| template | `string` | &#10004;&#65039; | `'labelTemplate'` | Defines how the cell should be rendered.

If `componentTemplate` is used you must define the `component` property as well.
| component | any | &#10004;&#65039; |  | Defines what component to use to render the cell.

Use with `template = 'componentTemplate'`.
| parent | any | &#10004;&#65039; |  | Defines what component to use to render the cell.

Use with `template = 'componentTemplate'`.
|===

[NOTE]
====
The `template` field can have the following values:

* `'labelTemplate'`
* `'labelBoldTemplate'`
* `'numericTemplate'`
* `'iconTemplate'`
* `'componentTemplate'`
====

[source, javascript]
.some.ts
----
...
this.columnSettings: DataTableColumnDefinition[] = [
  {
    field: 'atomicNumber',
    label: 'position',
    sortable: true,
    hideable: true,
    visible: true,
  },
  {
    field: 'type',
    label: 'Item type',
    valueFormatter: (type) => ('ITEM_TYPES.' + type)
    sortable: true,
    hideable: true,
    visible: true,
  },
  {
    label: 'name',
    sortable: true,
    template: 'labelBoldTemplate',
    hideable: true,
    visible: true,
  },
  {
    label: 'weight',
    valueGetter: (item) => (item.type === 'NET' ? item.netWeight : item.grossWeight)
    template: 'numericTemplate',
    sortable: true,
    hideable: true,
    visible: true,
  },
  {
    field: 'symbol',
    label: 'symbol',
    sortable: true,
    hideable: true,
    visible: true,
  },
  {
    field: 'actions',
    label: 'actions',
    sortable: false,
    hideable: false,
    visible: true,
    stickyEnd: true,
    template: 'componentTemplate',
    component: RowActionComponent,
  },
];
...
----

==== Table settings

|===
| Attribute | Binding | Type | Optional | Default | Description

| name | `@Input` | `string` | &#10004;&#65039; | `''` | Name of the table.
| dataSource | `@Input` | `any[] \| ServerSideDataSource \| MatTableDataSource` | &#10060; | `[]` | DataSource.
| columnSettings | `@Input` | `DataTableColumnDefinition[]` | &#10060; |  | Column settings.
| detailTemplate | `@Input` | `ngTemplateRef` | &#10004;&#65039; | `#defaultTemplate` | Custom user defined *detail* view
| showDetails |`@Input`  | `boolean` | &#10004;&#65039; | `false` | Flag indicating to render with *detail* rows.
| useSelection | `@Input` | `boolean` | &#10004;&#65039; | `false` | Flag to render with checkboxes for multiselect rows.
| color | `@Input` | `ThemePalette` | &#10004;&#65039; | `primary` | Use this palette for mat elements.
| showColumnMenu | `@Input` | `boolean` | &#10004;&#65039; | `false` | Flag to render column menu.
| hasSorting | `@Input` | `boolean` | &#10004;&#65039; | `false` | Flag to enable sorting.
| fixedHeader | `@Input` | `boolean` | &#10004;&#65039; | `false` | Flag to have sticky header.
| detailClosedIcon | `@Input` | `string` | &#10004;&#65039; | `chevron-right` | Icon to use for closed details.
| detailOpenIcon | `@Input` | `string` | &#10004;&#65039; | `chevron-down` | Icon to use for opened details.
| rowClass | `@Input` | `function` | &#10004;&#65039; | `() => null` | Dynamically set per-row CSS class.
| rowClick | `@Output` | `RowClickEvent` | &#10004;&#65039; |  | Emitted row click event.
| cellClick | `@Output` | `CellClickEvent` | &#10004;&#65039; |  | Emitted cell click event.
| rowKeyDown | `@Output` | `RowKeyDownEvent` | &#10004;&#65039; |  | Emitted row onkeydown event.
|===

[source, xml]
.some.html
----
<ic-data-table
  [name]="'table'"
  [dataSource]="dataSource"
  [columnSettings]="columnSettings"
  [detailTemplate]="detailTemplate"
  [showDetails]="showDetails"
  [useSelection]="useSelection"
  [showColumnMenu]="showColumnMenu"
  [hasSorting]="hasSorting"
  [fixedHeader]="fixedHeader"
  (rowClick)="rowClick($event)"
  (cellClick)="cellClick($event)"
></ic-data-table>
----

==== DataSource configuration

[source, javascript]
.some.server-side-datasource.ts
----
...
this.data = new ServerSideDataSource(
  this.getStaticData.bind(this),
  'list',
  this.paginationParams,
  this.table.sort,
  this.table.rowSelection,
  this.paginatorIntl,
  this.cdRef,
  this.withDetail,
  false
);
...
----

[source, javascript]
.some.client-side-datasource.ts
----
...
this.data = new MatTableDataSource([]);
...
----

=== Examples

==== Run example project

[source, bash]
----
# Build a local version
npm run build:prod
npm run pack
# Switch directories
cd ./examples/icell-data-table-example/
# Edit the package.json to have the proper path to the tgz
#   "@i-cell/data-table": "file:../../i-cell-data-table-<version>.tgz",
# Install dependencies
npm i
# Start up the example
npm start
----

If no issues emerge the application should up and running, so you can start to experiment.
