#!/bin/bash
ASCIIDOCTOR_BIN=`command -v asciidoctor`
PANDOC_BIN=`command -v pandoc`

# Detect OS
OS=$(uname -s)

if ! [ -x "$ASCIIDOCTOR_BIN" ]; then
  case "$OS" in
    Linux)
      sudo apt update && sudo apt install -y asciidoctor
      ;;
    Darwin)
      brew install asciidoctor
      ;;
    *)
      echo "Unsupported OS for Asciidoctor installation"
      exit 1
      ;;
  esac
  ASCIIDOCTOR_BIN=$(command -v asciidoctor)
fi
if ! [ -x "$PANDOC_BIN" ]; then
  case "$OS" in
    Linux)
      sudo apt update && sudo apt install -y pandoc
      ;;
    Darwin)
      brew install pandoc
      ;;
    *)
      echo "Unsupported OS for Pandoc installation"
      exit 1
      ;;
  esac
  PANDOC_BIN=$(command -v pandoc)
fi

$ASCIIDOCTOR_BIN -b docbook ./README.adoc
$PANDOC_BIN -f docbook -t gfm ./README.xml -o ./README.md