#!/bin/bash
ASCIIDOCTOR_BIN=`command -v asciidoctor`
PANDOC_BIN=`command -v pandoc`

if ! [ -x $ASCIIDOCTOR_BIN ]; then
  sudo apt install asciidoctor
  ASCIIDOCTOR_BIN=`command -v asciidoctor`
fi
if ! [ -x $PANDOC_BIN ]; then
  sudo wget https://github.com/jgm/pandoc/releases/download/2.0.0.1/pandoc-2.0.0.1-1-amd64.deb
  sudo dpkg -i pandoc-2.0.0.1-1-amd64.deb
  PANDOC_BIN=`command -v pandoc`
fi

$ASCIIDOCTOR_BIN -b docbook ./README.adoc
$PANDOC_BIN -f docbook -t gfm ./README.xml -o ./README.md
