# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - name: Install asciidoctor
      run: sudo apt install asciidoctor
    - name: Install pandoc
      run: sudo wget https://github.com/jgm/pandoc/releases/download/2.0.0.1/pandoc-2.0.0.1-1-amd64.deb; sudo dpkg -i pandoc-2.0.0.1-1-amd64.deb
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm i
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Lint
      run: npm run lint
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Create README markdown for npmjs.org
      run: npm run docs:readme
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build
      run: npm run build:prod
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Cleanup
      run: npm run docs:cleanup
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
