# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Publish

on:
  release:
    types: [created]
  pull_request:
    branches:
      - 'releases/**'
      - '!releases/**-alpha'

jobs:
  build:
    name: Publish

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - name: Install asciidoctor
      run: sudo apt install asciidoctor
    - name: Install pandoc
      run: sudo wget https://github.com/jgm/pandoc/releases/download/2.0.0.1/pandoc-2.0.0.1-1-amd64.deb; sudo dpkg -i pandoc-2.0.0.1-1-amd64.deb
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Publish release
      run: npm run publish:dist
    - name: Cleanup
      run: npm run docs:cleanup
